services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_test
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true

volumes:
  mongo_data:
    driver: local
