services:
  dev:
    image: node:20
    container_name: agendavip_dev
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true