services:
  api:
    container_name: agendabackend_${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true