services:
  frontend_${NODE_ENV}:
    container_name: agendafrontend_${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_URL: ${BACKEND_URL}
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true